# Generated by Django 5.1 on 2024-08-17 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAccess', '0005_customuser_address_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
